package proyecto_pdoo.Components;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import proyecto_pdoo.*;

/**
 *
 * @author forza
 */
public class Mejoras_compra extends javax.swing.JPanel {
    
    Mejoras mejora;
    Vista panel;
    
    public Mejoras_compra(Mejoras mejora, Vista data_panel) {
        initComponents();
        this.mejora = mejora;
        this.panel = data_panel;
        this.label_nombre.setText(mejora.getName() + " - " + mejora.getPrize());
        this.label_descripcion.setText(mejora.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        boton_comprar = new javax.swing.JButton();
        panel_descripcion = new javax.swing.JPanel();
        label_descripcion = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(431, 142));

        label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nombre.setText("NAME");

        boton_comprar.setBackground(new java.awt.Color(102, 204, 0));
        boton_comprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_comprar.setForeground(new java.awt.Color(255, 255, 255));
        boton_comprar.setText("BUY");
        boton_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comprarActionPerformed(evt);
            }
        });

        panel_descripcion.setLayout(new java.awt.CardLayout());

        label_descripcion.setText("Description");
        label_descripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_descripcion.add(label_descripcion, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_comprar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comprarActionPerformed
        if(mejora.buyUpgrade()){
            if(mejora.getTipo().equals(TipoMejoras.MEJORAS_MONEDAS)){
                Mejoras_inventario m = new Mejoras_inventario(label_nombre.getText(), label_descripcion.getText(), mejora.getPrize());
                panel.getPanelInventory().add(m);
                m.setVisible(true);
                m.setSize(300,141);
                panel.getPanelInventory().validate();
                panel.getPanelInventory().setVisible(true);
                panel.getPanelInventory().repaint();
                
                Mejoras_monedas mej = (Mejoras_monedas) mejora;
                mej.addCoinsClick();
                
                panel.reloadData();
            } else if(mejora.getTipo().equals(TipoMejoras.MEJORAS_EXPERIENCIA)){
                Mejoras_inventario m = new Mejoras_inventario(label_nombre.getText(), label_descripcion.getText(), mejora.getPrize());
                panel.getPanelInventory().add(m);
                m.setVisible(true);
                m.setSize(300,141);
                panel.getPanelInventory().validate();
                panel.getPanelInventory().setVisible(true);
                panel.getPanelInventory().repaint();
                
                Mejoras_experiencia mej = (Mejoras_experiencia) mejora;
                mej.addExpPerClic();
                
                panel.reloadData();
            }
            else if(mejora.getTipo().equals(TipoMejoras.MEJORAS_TIEMPO)){
                Mejoras_tiempo_inventario m = new Mejoras_tiempo_inventario(label_nombre.getText(), label_descripcion.getText(), mejora.getPrize());
                panel.getPanelInventory().add(m);
                m.setVisible(true);
                m.setSize(300,141);
                panel.getPanelInventory().validate();
                panel.getPanelInventory().setVisible(true);
                panel.getPanelInventory().repaint();
                
                Mejoras_tiempo mej = (Mejoras_tiempo) mejora;
                mej.autoClicks();
                
                panel.reloadData();
            }
        }else{
            System.out.println("No tienes suficiente dinero");
        }
    }//GEN-LAST:event_boton_comprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_comprar;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JPanel panel_descripcion;
    // End of variables declaration//GEN-END:variables

    //------------------------------GETTERS Y SETTERS-----------------------------------
    
    //-----Boton comprar
    
    public JButton getBoton_comprar() {
        return boton_comprar;
    }

    public void setBoton_comprar(JButton boton_comprar) {
        this.boton_comprar = boton_comprar;
    }

    //-----Label descripcion
    
    public JLabel getLabel_descripcion() {
        return label_descripcion;
    }

    public void setLabel_descripcion(JLabel label_descripcion) {
        this.label_descripcion = label_descripcion;
    }

    //-----Label nombre
    
    public JLabel getLabel_nombre() {
        return label_nombre;
    }

    public void setLabel_nombre(JLabel label_nombre) {
        this.label_nombre = label_nombre;
    }

    //-----Panel descripcion
    
    public JPanel getPanel_descripcion() {
        return panel_descripcion;
    }

    public void setPanel_descripcion(JPanel panel_descripcion) {
        this.panel_descripcion = panel_descripcion;
    }

    
    
}
