package proyecto_pdoo.Components;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author forza
 */
public class Mejoras_inventario extends javax.swing.JPanel {
    
    private int precio;

    /**
     * Creates new form Upgrades_buy
     */
    public Mejoras_inventario(String nombre, String descripcion, int precio) {
        initComponents();
        label_nombre.setText(nombre);
        label_descripcion.setText(descripcion);
        this.precio = precio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        boton_vender = new javax.swing.JButton();
        panel_descripcion = new javax.swing.JPanel();
        label_descripcion = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(431, 142));

        label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nombre.setText("NAME");

        boton_vender.setBackground(new java.awt.Color(255, 0, 0));
        boton_vender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_vender.setForeground(new java.awt.Color(255, 255, 255));
        boton_vender.setText("VENDER");
        boton_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_venderActionPerformed(evt);
            }
        });

        panel_descripcion.setLayout(new java.awt.CardLayout());

        label_descripcion.setText("Description");
        label_descripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_descripcion.add(label_descripcion, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_vender)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_venderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_venderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_vender;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JPanel panel_descripcion;
    // End of variables declaration//GEN-END:variables

    //------------------------------GETTERS Y SETTERS-----------------------------------
    
    //-----Boton vender
    
    public JButton getBoton_vender() {
        return boton_vender;
    }

    public void setBoton_vender(JButton boton_comprar) {
        this.boton_vender = boton_comprar;
    }

    //-----Label descripcion
    
    public JLabel getLabel_descripcion() {
        return label_descripcion;
    }

    public void setLabel_descripcion(JLabel label_descripcion) {
        this.label_descripcion = label_descripcion;
    }

    //-----Label nombre
    
    public JLabel getLabel_nombre() {
        return label_nombre;
    }

    public void setLabel_nombre(JLabel label_nombre) {
        this.label_nombre = label_nombre;
    }

    //-----Panel descripcion
    
    public JPanel getPanel_descripcion() {
        return panel_descripcion;
    }

    public void setPanel_descripcion(JPanel panel_descripcion) {
        this.panel_descripcion = panel_descripcion;
    }

    
    
}
